### PR TITLE
Corrections To My Index Page

### PR DESCRIPTION
**Pull request by chibytez**
making the index page to be responsive and also to fit higher resolutions. Changing the background picture to white. changing the white delivery picture to black
ft-index-160210331
What does this PR do?

#### Description of Task to be completed?
changing the background color to white.
making the page responsive to bigger screens.
changing the color of the white delivery bike 
changing the font color to black

#### What are the relevant pivotal tracker stories?
#160210331
#### Screenshots
before
beforeindex

after

afterindex

### CODE REVIEW

**Comment by robocopkaka** [comment]
Hi, few changes you should make:
* Noticed you have put in your entire PT description. Just the PT ID should suffice
* Also, the parts before `What does this PR do?` should be removed since `Description of task to be completed` already covers it

**Comment by chibytez** [comment]
> Hi, few changes you should make:
> 
> * Noticed you have put in your entire PT description. Just the PT ID should suffice
> * Also, the parts before `What does this PR do?` should be removed since `Description of task to be completed` already covers it

thank you, corrections have been made

**Comment by robocopkaka** [comment]
Please add `What does this PR do?` to the top of the PR description. Guess I wasn't clear initially. You can merge this once you've done that.

Example:
```
What does the PR do?
...what it does
```

**Comment by chibytez** [comment]
> Please add `What does this PR do?` to the top of the PR description. Guess I wasn't clear initially. You can merge this once you've done that.
> 
> Example:
> 
> ```
> What does the PR do?
> ...what it does
> ```

ok thanks alot

**Pull request merged**
